import type { ControlTowerOverviewDto } from './api-client';

const now = new Date();
const day = (n:number) => new Date(now.getTime()+n*86400000).toISOString();
const projects = [
{id:'preview-arad',name:'Parc Solar Arad',code:'AR-001',address:'Arad, Romania',status:'CONSTRUCTION',progress:68,budget_total:1850000,currency:'RON',target_end_date:day(1)},
{id:'preview-tm',name:'Parc Solar Timisoara',code:'TM-002',address:'Timisoara, Romania',status:'CONSTRUCTION',progress:52,budget_total:1420000,currency:'RON',target_end_date:day(5)},
{id:'preview-cj',name:'Parc Solar Cluj',code:'CJ-003',address:'Cluj-Napoca, Romania',status:'TESTING',progress:81,budget_total:2100000,currency:'RON',target_end_date:day(9)}
];
const tasks=[
{id:'preview-t1',project_id:'preview-arad',code:'AR-001-T02',title:'Montaj 120 module fotovoltaice 450 Wp',status:'IN_PROGRESS',planned_quantity:120,actual_quantity:48,unit_of_measure:'buc',planned_start:day(-2),planned_end:day(1)},
{id:'preview-t2',project_id:'preview-arad',code:'AR-001-T03',title:'Cablare DC - 6 string-uri',status:'READY',planned_quantity:6,actual_quantity:2,unit_of_measure:'string',planned_start:day(0),planned_end:day(1)},
{id:'preview-t3',project_id:'preview-tm',code:'TM-002-T02',title:'Montaj module fotovoltaice zona A',status:'IN_PROGRESS',planned_quantity:96,actual_quantity:40,unit_of_measure:'buc',planned_start:day(-1),planned_end:day(2)},
{id:'preview-t4',project_id:'preview-cj',code:'CJ-003-T04',title:'Racordare la retea - verificare finala',status:'PLANNED',planned_quantity:1,actual_quantity:0,unit_of_measure:'buc',planned_start:day(1),planned_end:day(3)}
];
const dailyPlans=[{id:'preview-plan',project_id:'preview-arad',team_id:'preview-team-arad',plan_date:now.toISOString().slice(0,10),status:'PUBLISHED',notes:'Plan demo — Echipa Montaj Arad 1',created_by:'preview-team-leader',created_at:now.toISOString(),updated_at:now.toISOString(),project:{id:projects[0].id,name:projects[0].name,code:projects[0].code},team:{id:'preview-team-arad',name:'Echipa Montaj Arad 1',code:'AR-E1'},tasks:tasks.slice(0,3).map((t,i)=>({id:'preview-pt-'+i,daily_plan_id:'preview-plan',task_id:t.id,target_quantity:i===0?24:i===1?2:20,actual_quantity:i===0?16:i===1?1:20,completed:i===2,task:{id:t.id,title:t.title,code:t.code,status:t.status,unit_of_measure:t.unit_of_measure,assignments:[{id:'a'+i,task_id:t.id,user_id:'preview-worker',assigned_at:now.toISOString(),user:{id:'preview-worker',email:'worker.preview@hiieko.local',fullName:'Preview Worker'}}]}}))}];
const findProject=(id:string)=>projects.find(p=>p.id===id)!;
const overview:ControlTowerOverviewDto={
projects:{activeProjects:3,projectsByStage:{CONSTRUCTION:2,TESTING:1},upcomingDeadlines:2,overdueProjects:0,activeProjectsList:projects.map(p=>({id:p.id,name:p.name,code:p.code,stage:p.status,targetEndDate:p.target_end_date,budgetTotal:p.budget_total,currency:p.currency,progressPercent:p.progress})),upcomingDeadlinesList:[{id:'d1',projectId:projects[0].id,projectName:projects[0].name,projectCode:'AR-001',stage:'Montaj module',targetDate:day(1),daysUntilDeadline:1,responsiblePerson:'Preview Site Manager'},{id:'d2',projectId:projects[1].id,projectName:projects[1].name,projectCode:'TM-002',stage:'Cablare AC',targetDate:day(5),daysUntilDeadline:5,responsiblePerson:'Preview PM'}],overdueProjectsList:[]},
workforce:{scheduledToday:12,checkedIn:9,missing:3,overtimeMinutes:135,scheduledTodayList:[],missingList:[{userId:'preview-worker-2',fullName:'Preview Worker 2',projectId:projects[1].id,projectName:projects[1].name,projectCode:'TM-002',role:'worker',expectedAt:'08:00',responsiblePerson:'Preview Foreman'}],overtimeList:[{userId:'preview-foreman',fullName:'Preview Foreman',projectId:projects[0].id,projectName:projects[0].name,projectCode:'AR-001',overtimeMinutes:75,overtimeHours:'1h 15m'}]},
production:{plannedToday:46,actualToday:37,completionPercentage:80,blockedProduction:1,plannedTasksList:tasks.map(t=>({id:t.id,taskCode:t.code,title:t.title,projectId:t.project_id,projectName:findProject(t.project_id).name,projectCode:findProject(t.project_id).code,zoneName:'Zona 1',plannedStart:t.planned_start,plannedEnd:t.planned_end,plannedQuantity:t.planned_quantity,unitOfMeasure:t.unit_of_measure,assignedWorkers:['Preview Worker','Preview Technician']})),actualTasksList:tasks.slice(0,3).map(t=>({id:t.id,taskCode:t.code,title:t.title,projectId:t.project_id,projectName:findProject(t.project_id).name,projectCode:findProject(t.project_id).code,actualStart:t.planned_start,actualEnd:null,actualQuantity:t.actual_quantity,completionPercent:t.planned_quantity?Math.round(t.actual_quantity/t.planned_quantity*100):0,assignedWorkers:['Preview Worker']})),blockedTasksList:[{id:'blocked-1',taskCode:'TM-002-T03',title:'Montaj invertor si tablou AC',projectId:projects[1].id,projectName:projects[1].name,projectCode:'TM-002',zoneName:'Zona 1',blockedReason:'Material delivery pending',blockingTasks:[],assignedWorkers:['Preview Technician'],responsiblePerson:'Preview Site Manager'}]},
materials:{lowStock:2,missingRequired:1,overconsumption:1,pendingDeliveries:2,lowStockList:[{materialId:'m1',materialCode:'MOD-450',materialName:'Module fotovoltaic 450 Wp',unit:'buc',currentQuantity:28,minThreshold:50,projectId:projects[0].id,projectName:projects[0].name,warehouseId:'wh1',warehouseName:'Depozit Arad',deficit:22}],missingRequiredList:[{materialId:'m2',materialCode:'INV-50',materialName:'Invertor 50 kW',unit:'buc',projectId:projects[1].id,projectName:projects[1].name,projectCode:'TM-002',requiredQuantity:2,availableQuantity:1,shortfall:1,taskId:tasks[2].id,taskCode:tasks[2].code}],overconsumptionList:[],pendingDeliveriesList:[{id:'av1',avizNumber:'AVZ-2026-014',supplierName:'Demo Solar Supply',deliveryDate:day(1),projectId:projects[1].id,projectName:projects[1].name,projectCode:'TM-002',items:[{materialId:'m2',materialCode:'INV-50',materialName:'Invertor 50 kW',quantity:1,unit:'buc'}],status:'PENDING'}]},
finance:{budget:5370000,actual:2985000,committed:760000,forecast:5100000,variance:270000,variancePercent:5,budgetByProject:projects.map(p=>({projectId:p.id,projectName:p.name,projectCode:p.code,budget:p.budget_total,actual:Math.round(p.budget_total*.55),committed:Math.round(p.budget_total*.14),forecast:Math.round(p.budget_total*.95),variance:Math.round(p.budget_total*.05),variancePercent:5,currency:'RON'}))},
quality:{failedInspections:1,openNCRs:2,pendingCorrections:2,failedInspectionsList:[{id:'ins1',projectId:projects[1].id,projectName:projects[1].name,projectCode:'TM-002',inspectorName:'Preview QA / QC',inspectedAt:day(-1),failedParameters:[{parameter:'String voltage',value:31.2,unit:'V',passed:false}],responsiblePerson:'Preview Technician'}],openNCRsList:[{id:'ncr1',ncrNumber:'NCR-026',projectId:projects[0].id,projectName:projects[0].name,projectCode:'AR-001',description:'Two roof hooks require resealing.',status:'OPEN',createdAt:day(-1),responsiblePerson:'Preview Foreman'}],pendingCorrectionsList:[]},
documentation:{missingDocuments:1,awaitingApproval:2,supersededDocuments:1,missingDocumentsList:[{projectId:projects[2].id,projectName:projects[2].name,projectCode:'CJ-003',requiredDocumentType:'As-built drawing',reason:'Final revision not uploaded',responsiblePerson:'Preview PM'}],awaitingApprovalList:[],supersededDocumentsList:[]},
redFlags:[{id:'flag1',category:'MATERIALS',affectedEntity:'Invertor 50 kW',entityId:'m2',reason:'One unit short for TM-002 installation.',responsiblePerson:'Preview Procurement',responsiblePersonId:'preview-procurement',timestamp:now.toISOString(),sourceRecord:'stock_balances',sourceRecordId:'m2',severity:'HIGH'}]
};
export function isPreviewMode(){return typeof window!=='undefined'&&sessionStorage.getItem('hiieko_role_preview')!==null;}
export function getPreviewResponse(endpoint:string):any|null{
if(!isPreviewMode())return null;
if(endpoint.startsWith('/api/control-tower/overview'))return {data:overview};
if(endpoint.startsWith('/api/control-tower/red-flags'))return {data:overview.redFlags};
if(endpoint.startsWith('/api/projects'))return {data:projects};
if(endpoint.startsWith('/api/tasks'))return {data:tasks};
if(endpoint.startsWith('/api/daily-plans/my-tasks'))return {data:dailyPlans};
if(endpoint.startsWith('/api/daily-plans'))return {data:dailyPlans};
if(endpoint.startsWith('/api/teams'))return {data:[{id:'preview-team-arad',name:'Echipa Montaj Arad 1',code:'AR-E1',project_id:projects[0].id,leader_id:'preview-team-leader',is_active:true},{id:'preview-team-tm',name:'Echipa Montaj Timisoara 1',code:'TM-E1',project_id:projects[1].id,leader_id:'preview-team-leader',is_active:true},{id:'preview-team-cj',name:'Echipa Montaj Cluj 1',code:'CJ-E1',project_id:'preview-team-leader',leader_id:'preview-team-leader',is_active:true}]};
if(endpoint.startsWith('/api/issues'))return {data:[{id:'i1',projectId:projects[0].id,title:'Roof hook sealing correction',description:'Two hooks need resealing.',severity:'HIGH',status:'OPEN',createdAt:day(-1),project:projects[0]},{id:'i2',projectId:projects[1].id,title:'Inverter delivery delay',description:'One inverter is still pending.',severity:'MEDIUM',status:'IN_PROGRESS',createdAt:now.toISOString(),project:projects[1]}]};
if(endpoint.startsWith('/api/expenses'))return {data:[{id:'e1',projectId:projects[0].id,description:'Transport module',amount:18400,currency:'RON',status:'PENDING',date:now.toISOString(),submittedBy:'Preview Site Manager'},{id:'e2',projectId:projects[1].id,description:'Crane rental',amount:9600,currency:'RON',status:'APPROVED',date:day(-1),submittedBy:'Preview Foreman'}]};
if(endpoint.startsWith('/api/notifications'))return {data:[{id:'n1',title:'Material delivery pending',message:'TM-002 needs one inverter.',createdAt:now.toISOString(),isRead:false,type:'WARNING'},{id:'n2',title:'Inspection failed',message:'String voltage needs correction.',createdAt:day(-1),isRead:false,type:'QUALITY'}]};
if(endpoint.startsWith('/api/attendance/my-logs'))return {data:[{id:'att1',date:now.toISOString(),check_in_time:day(-0.02),check_out_time:null,project_id:projects[0].id}]};
if(endpoint.startsWith('/api/attendance'))return {data:[{id:'att1',date:now.toISOString(),user_id:'preview-worker',full_name:'Preview Worker',project_id:projects[0].id,check_in_time:day(-0.02),check_out_time:null}]};
if(endpoint.startsWith('/api/users'))return {data:[{id:'preview-admin',email:'admin.preview@hiieko.local',role:'admin',fullName:'Preview Administrator',is_active:true},{id:'preview-pm',email:'pm.preview@hiieko.local',role:'pm',fullName:'Preview Project Manager',is_active:true},{id:'preview-worker',email:'worker.preview@hiieko.local',role:'worker',fullName:'Preview Worker',is_active:true}]};
if(endpoint.startsWith('/api/employees'))return {data:[{id:'emp1',user_id:'preview-worker',first_name:'Preview',last_name:'Worker',position:'Muncitor montaj',hourly_rate:32,is_active:true},{id:'emp2',user_id:'preview-technician',first_name:'Preview',last_name:'Technician',position:'Tehnician electric',hourly_rate:38,is_active:true}]};
if(endpoint.startsWith('/api/inventory/stock'))return {data:[{id:'stock1',materialId:'m1',materialCode:'MOD-450',materialName:'Module fotovoltaic 450 Wp',quantity:28,unit:'buc',projectId:projects[0].id,projectName:projects[0].name},{id:'stock2',materialId:'m2',materialCode:'INV-50',materialName:'Invertor 50 kW',quantity:1,unit:'buc',projectId:projects[1].id,projectName:projects[1].name}]};
if(endpoint.startsWith('/api/materials'))return {data:[{id:'m1',code:'MOD-450',name:'Module fotovoltaic 450 Wp',unit:'buc'},{id:'m2',code:'INV-50',name:'Invertor 50 kW',unit:'buc'},{id:'m3',code:'CABL-6',name:'Cablu solar 6 mm²',unit:'m'}]};
if(endpoint.startsWith('/api/suppliers'))return {data:[{id:'sup1',name:'Demo Solar Supply',cui:'RO12345678',contact_person:'Alex Demo'},{id:'sup2',name:'Electro Demo SRL',cui:'RO87654321',contact_person:'Maria Demo'}]};
if(endpoint.startsWith('/api/warehouses'))return {data:[{id:'wh1',name:'Depozit Arad',code:'AR-WH-01',address:'Arad'},{id:'wh2',name:'Depozit Central',code:'HQ-WH-01',address:'Timisoara'}]};
if(endpoint.startsWith('/api/procurement/delivery-notes'))return {data:[{id:'av1',avizNumber:'AVZ-2026-014',deliveryDate:day(1),status:'PENDING',supplier:{name:'Demo Solar Supply'},project:projects[1],items:[]}]};
if(endpoint.startsWith('/api/procurement/purchase-orders'))return {data:[{id:'po1',number:'PO-2026-031',status:'PENDING',supplier:{name:'Demo Solar Supply'},total:42000,currency:'RON',project:projects[1]}]};
if(endpoint.startsWith('/api/qa-qc/inspections'))return {data:[{id:'ins1',projectId:projects[1].id,inspectorName:'Preview QA / QC',status:'FAILED',inspectedAt:day(-1),result:'FAILED',project:projects[1]},{id:'ins2',projectId:projects[0].id,inspectorName:'Preview QA / QC',status:'COMPLETED',inspectedAt:now.toISOString(),result:'PASSED',project:projects[0]}]};
if(endpoint.startsWith('/api/daily-reports'))return {data:[{id:'r1',projectId:projects[0].id,reportDate:now.toISOString(),status:'SUBMITTED',project:projects[0],createdBy:'Preview Site Manager',summary:'Module installation progressing normally.'},{id:'r2',projectId:projects[1].id,reportDate:day(-1),status:'DRAFT',project:projects[1],createdBy:'Preview Foreman',summary:'Awaiting inverter delivery.'}]};
if(endpoint.startsWith('/api/documents'))return {data:[{id:'doc1',title:'Raport zilnic CJ-003',documentType:'DAILY_REPORT',status:'PENDING_APPROVAL',version:1,project:projects[2]},{id:'doc2',title:'Plan montaj AR-001',documentType:'WORK_PLAN',status:'SUPERSEDED',version:1,project:projects[0]}]};
return null;
}