-- Slice 5 — global one-open-session-per-user invariant (DB-enforced).
--
-- Enforces "no user may have more than one open attendance session" at the
-- database level, independent of application logic. The predicate
-- `check_out_time IS NULL` keeps the index very small and only ever touches
-- currently-open sessions, so it adds no write overhead to completed records.
--
--   UNIQUE(user_id) WHERE check_out_time IS NULL
--
-- This is intentionally a PARTIAL unique index: a user is still allowed to
-- have MANY completed (checked-out) sessions on the same day. Only the open
-- one is unique.
--
-- This is NOT generated by `prisma migrate dev` (Prisma has no first-class
-- partial-index support), so it lives in its own idempotent, manual migration.
-- It is run before the application's check-in ConflictException: both layers
-- defend the same invariant — the DB index is the final authority under
-- concurrency, and the service ConflictException is the friendly surface.

CREATE UNIQUE INDEX IF NOT EXISTS "attendance_records_single_open_session_idx"
  ON "attendance_records"("user_id")
  WHERE "check_out_time" IS NULL;
